### ISSUE TITLE
Adopt `FakeTensorMode` for FSDP

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#16448]
### Description & Motivation

Currently, very large models can't be instantiated before sharding if they don't fit in CPU memory. The solution to this, and similar to how other libraries like deepspeed do it, is to create fake tensors that don't allocate memory, then shard them, and only materialze them once sharded on each device. 

### Pitch

Adopt the [FakeTensorMode](https://github.com/pytorch/pytorch/blob/master/torch/_subclasses/fake_tensor.py#L721) context manager. It is not officially documented, but we can start experimenting it in Fabric.

The usage in PyTorch would be:

```py
with FakeTensorMode():
    model = MyModel(...)  # tensors are fake and don't allocate memory
```

This would translate to 
```py
with fabric.sharded_model():
    model = MyModel(...)
```

in Fabric.

### Alternatives

A similar mechanism exists in [torchdistx](https://github.com/pytorch/torchdistx/blob/2071f8b4ae2325487f5e555f48fc21c9161aae98/src/python/torchdistx/deferred_init.py).

### Additional context

Proposed by @justusschock 

_No response_

cc @borda @carmocca @justusschock @awaelchli

**Comment by carmocca** [comment]
We'd want to replace our existing `torchdistx` logic:
https://github.com/Lightning-AI/lightning/blob/39acb81b9bd01139f7cead31c673f25ba330f2f1/src/pytorch_lightning/trainer/trainer.py#L1184-L1188
https://github.com/Lightning-AI/lightning/blob/39acb81b9bd01139f7cead31c673f25ba330f2f1/src/pytorch_lightning/utilities/meta.py
https://github.com/Lightning-AI/lightning/blob/39acb81b9bd01139f7cead31c673f25ba330f2f1/tests/tests_pytorch/utilities/test_torchdistx.py

@eellison (author in PyTorch): is there any public docs or design documents that we can look at about this new mode? Does it completely replace deferred initialization as currently implemented in `torchdistx`?

**Comment by awaelchli** [comment]
Update: FakeTensorMode doesn't yet work well with FSDP in PT 2.0. If a module gets instantiated with fake tensors, we get this error when attempting to wrap it with the FSDP module:

```
 _init_param_handle_from_params(state, managed_params, fully_sharded_module)
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/_init_utils.py", line 525, in _init_param_handle_from_params
    handle = FlatParamHandle(
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/flat_param.py", line 361, in __init__
    self._init_flat_param(params, fully_sharded_module, use_orig_params)
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/flat_param.py", line 470, in _init_flat_param
    self.flat_param._init_metadata(
AttributeError: 'FakeTensor' object has no attribute '_init_metadata'
Traceback (most recent call last):
  File "/home/adrian/repositories/lightning/fsdp_testing.py", line 16, in <module>
    fabric_model = fabric.setup_module(large_model)
  File "/home/adrian/repositories/lightning/src/lightning/fabric/fabric.py", line 245, in setup_module
    module = self._strategy.setup_module(module)
  File "/home/adrian/repositories/lightning/src/lightning/fabric/strategies/fsdp.py", line 192, in setup_module
    wrapped_module = FullyShardedDataParallel(
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 408, in __init__
    _init_param_handle_from_module(
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/_init_utils.py", line 429, in _init_param_handle_from_module
    _init_param_handle_from_params(state, managed_params, fully_sharded_module)
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/_init_utils.py", line 525, in _init_param_handle_from_params
    handle = FlatParamHandle(
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/flat_param.py", line 361, in __init__
    self._init_flat_param(params, fully_sharded_module, use_orig_params)
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/flat_param.py", line 470, in _init_flat_param
    self.flat_param._init_metadata(
AttributeError: 'FakeTensor' object has no attribute '_init_metadata'

```

**Comment by eellison** [comment]
@carmocca pytorch tracking issue here: https://github.com/pytorch/pytorch/issues/93947. As you have seen, doesn't work currently, but it's on our radar.

**Comment by awaelchli** [comment]
Another issue #96161 is tracking this as well <3
