### ISSUE TITLE
Support for torch without distributed broken

### ISSUE THREAD

**Issue by adamjstewart** [Lightning-AI/lightning#18858]
### Bug description

PyTorch on macOS rarely comes with distributed support (MPI isn't needed on a single CPU). For example, on my system:
```pycon
> python
>>> import torch
>>> torch.distributed.is_available()
False
>>> torch.distributed.is_initialized()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
```
New lightning releases have frequently had issues with PyTorch when distributed support is not available:

* 1.5.0: #10348
* 1.8.0: #15494 
* 1.9.0: #16637 

Unfortunately, this is broken once again in 2.1.0. It appears that this was broken in #17408. The issue is that all calls to `lightning.fabric.utlities.distributed. _distributed_available` (which checks `is_available` before `is_initialized`) were replaced with calls to `is_initialized`, which fails. This was even noted during PR review: https://github.com/Lightning-AI/lightning/pull/17408/files#r1171085018.

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
Haven't yet found a simple minimal reproducer but it should be obvious what the issue is and how to fix it.
```

### Error messages and logs

```
  File "/Users/Adam/torchgeo/test.py", line 18, in <module>
    trainer.fit(
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 137, in run
    self.on_advance_end(data_fetcher)
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 285, in on_advance_end
    self.val_loop.run()
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 140, in run
    self._store_dataloader_outputs()
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 336, in _store_dataloader_outputs
    self._logged_outputs.append(trainer._logger_connector.update_eval_epoch_metrics())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/logger_connector/logger_connector.py", line 130, in update_eval_epoch_metrics
    metrics = self.metrics
              ^^^^^^^^^^^^
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/logger_connector/logger_connector.py", line 226, in metrics
    return self.trainer._results.metrics(on_step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/logger_connector/result.py", line 471, in metrics
    value = self._get_cache(result_metric, on_step)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/logger_connector/result.py", line 428, in _get_cache
    if not should and result_metric.is_tensor and torch.distributed.is_initialized():
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
	- GPU:               None
	- available:         False
	- version:           None
* Lightning:
	- efficientnet-pytorch: 0.7.1
	- lightning:         2.1.0
	- lightning-utilities: 0.8.0
	- pytorch-lightning: 2.0.0
	- pytorch-sphinx-theme: 0.0.24
	- segmentation-models-pytorch: 0.3.3
	- torch:             2.1.0
	- torchmetrics:      1.2.0
	- torchvision:       0.16.0
* Packages:
	- absl-py:           1.4.0
	- aenum:             3.1.12
	- affine:            2.1.0
	- aiohttp:           3.8.4
	- aiosignal:         1.2.0
	- alabaster:         0.7.13
	- antlr4-python3-runtime: 4.9.3
	- anyio:             4.0.0
	- appdirs:           1.4.4
	- appnope:           0.1.3
	- argon2-cffi:       21.3.0
	- argon2-cffi-bindings: 21.2.0
	- arrow:             1.2.3
	- asttokens:         2.4.0
	- astunparse:        1.6.3
	- async-lru:         1.0.3
	- async-timeout:     4.0.2
	- attrs:             23.1.0
	- babel:             2.12.1
	- backcall:          0.2.0
	- beautifulsoup4:    4.12.2
	- black:             23.9.1
	- bleach:            6.0.0
	- bottleneck:        1.3.7
	- build:             1.0.3
	- cachetools:        5.2.0
	- cartopy:           0.22.0
	- certifi:           2023.5.7
	- cffi:              1.15.1
	- cftime:            1.0.3.4
	- charset-normalizer: 3.1.0
	- click:             8.1.3
	- click-plugins:     1.1.1
	- cligj:             0.7.2
	- cmocean:           2.0
	- colorama:          0.4.6
	- comm:              0.1.3
	- conda-souschef:    2.2.3
	- contourpy:         1.0.7
	- coverage:          7.2.6
	- cycler:            0.11.0
	- debugpy:           1.6.7
	- decorator:         5.1.1
	- defusedxml:        0.7.1
	- docstring-parser:  0.15
	- docutils:          0.18.1
	- editables:         0.3
	- efficientnet-pytorch: 0.7.1
	- einops:            0.7.0
	- et-xmlfile:        1.0.1
	- executing:         1.2.0
	- fastjsonschema:    2.16.3
	- filelock:          3.12.4
	- fiona:             1.9.4
	- flake8:            6.1.0
	- fonttools:         4.39.4
	- fqdn:              1.5.1
	- frozenlist:        1.3.1
	- fsspec:            2023.1.0
	- gdal:              3.7.2
	- geocube:           0.3.2
	- geopandas:         0.11.1
	- gevent:            23.7.0
	- google-auth:       2.20.0
	- google-auth-oauthlib: 0.5.2
	- grayskull:         2.5.0
	- greenlet:          2.0.2
	- grpcio:            1.52.0
	- h5py:              3.8.0
	- hatch-jupyter-builder: 0.8.3
	- hatchling:         1.18.0
	- huggingface-hub:   0.14.1
	- hydra-core:        1.3.1
	- idna:              3.4
	- imageio:           2.30.0
	- imagesize:         1.4.1
	- importlib-metadata: 6.6.0
	- importlib-resources: 5.12.0
	- iniconfig:         2.0.0
	- ipykernel:         6.23.1
	- ipython:           8.14.0
	- ipywidgets:        8.0.2
	- isoduration:       20.11.0
	- isort:             5.12.0
	- jaraco.classes:    3.2.3
	- jedi:              0.18.2
	- jinja2:            3.0.3
	- joblib:            1.2.0
	- json5:             0.9.14
	- jsonargparse:      4.19.0
	- jsonpointer:       2.0
	- jsonschema:        4.17.3
	- jupyter-client:    8.2.0
	- jupyter-core:      5.3.0
	- jupyter-events:    0.6.3
	- jupyter-lsp:       2.2.0
	- jupyter-server:    2.6.0
	- jupyter-server-terminals: 0.4.4
	- jupyterlab:        4.0.1
	- jupyterlab-pygments: 0.2.2
	- jupyterlab-server: 2.22.1
	- jupyterlab-widgets: 3.0.3
	- keyring:           23.13.1
	- kiwisolver:        1.4.4
	- kornia:            0.7.0
	- laspy:             2.2.0
	- lazy-loader:       0.1
	- lightly:           1.4.18
	- lightly-utils:     0.0.2
	- lightning:         2.1.0
	- lightning-utilities: 0.8.0
	- markdown:          3.4.1
	- markdown-it-py:    3.0.0
	- markupsafe:        2.1.3
	- matplotlib:        3.8.0
	- matplotlib-inline: 0.1.6
	- mccabe:            0.7.0
	- mdurl:             0.1.2
	- mistune:           2.0.5
	- more-itertools:    9.1.0
	- mpmath:            1.2.1
	- multidict:         6.0.4
	- munch:             2.5.0
	- mypy:              1.3.0
	- mypy-extensions:   1.0.0
	- nbclient:          0.6.7
	- nbconvert:         7.4.0
	- nbformat:          5.8.0
	- nbmake:            1.4.3
	- nbsphinx:          0.8.8
	- nest-asyncio:      1.5.6
	- netcdf4:           1.6.2
	- networkx:          3.1
	- notebook-shim:     0.2.3
	- numexpr:           2.8.4
	- numpy:             1.26.0
	- oauthlib:          3.2.1
	- odc-geo:           0.1.2
	- omegaconf:         2.3.0
	- openpyxl:          3.1.2
	- overrides:         7.3.1
	- packaging:         23.1
	- pandas:            1.5.2
	- pandocfilters:     1.5.0
	- parso:             0.8.3
	- pathspec:          0.11.1
	- pexpect:           4.8.0
	- pickleshare:       0.7.5
	- pillow:            10.0.0
	- pip:               23.1.2
	- pkginfo:           1.9.6
	- planetary-computer: 0.4.9
	- platformdirs:      3.10.0
	- pluggy:            1.0.0
	- pooch:             1.7.0
	- pretrainedmodels:  0.7.4
	- progressbar2:      3.55.0
	- prometheus-client: 0.17.0
	- prompt-toolkit:    3.0.38
	- protobuf:          3.20.3
	- psutil:            5.9.5
	- ptyprocess:        0.7.0
	- pure-eval:         0.2.2
	- pyasn1:            0.4.8
	- pyasn1-modules:    0.2.8
	- pybind11:          2.11.0
	- pycocotools:       2.0.6
	- pycodestyle:       2.11.0
	- pycparser:         2.21
	- pydantic:          1.10.9
	- pydocstyle:        6.2.1
	- pyflakes:          3.1.0
	- pygeos:            0.10
	- pygments:          2.16.1
	- pyparsing:         3.0.9
	- pyproj:            3.2.1
	- pyproject-hooks:   1.0.0
	- pyrsistent:        0.19.3
	- pyshp:             2.1.0
	- pystac:            1.4.0
	- pystac-client:     0.5.1
	- pytest:            7.3.2
	- pytest-cov:        4.0.0
	- python-dateutil:   2.8.2
	- python-dotenv:     0.19.2
	- python-json-logger: 2.0.7
	- python-utils:      3.5.2
	- pytorch-lightning: 2.0.0
	- pytorch-sphinx-theme: 0.0.24
	- pytz:              2023.3
	- pyupgrade:         3.3.1
	- pyvista:           0.37.0
	- pywavelets:        1.4.1
	- pyyaml:            6.0
	- pyzmq:             25.0.2
	- radiant-mlhub:     0.3.1
	- rapidfuzz:         3.3.1
	- rarfile:           4.1
	- rasterio:          1.3.8
	- readme-renderer:   37.3
	- requests:          2.31.0
	- requests-oauthlib: 1.3.1
	- requests-toolbelt: 1.0.0
	- rfc3339-validator: 0.1.4
	- rfc3986:           2.0.0
	- rfc3986-validator: 0.1.1
	- rich:              13.4.2
	- rioxarray:         0.4.1.post0
	- rsa:               4.9
	- rtree:             1.0.1
	- ruamel.yaml:       0.17.32
	- ruamel.yaml.clib:  0.2.7
	- ruamel.yaml.jinja2: 0.2.7
	- safetensors:       0.3.1
	- scikit-image:      0.20.0
	- scikit-learn:      1.3.1
	- scipy:             1.11.3
	- scooby:            0.5.7
	- segmentation-models-pytorch: 0.3.3
	- semver:            3.0.1
	- send2trash:        1.8.0
	- setuptools:        63.4.3
	- shapely:           1.8.0
	- six:               1.16.0
	- sniffio:           1.3.0
	- snowballstemmer:   2.2.0
	- snuggs:            1.4.1
	- soupsieve:         2.4.1
	- sphinx:            5.3.0
	- sphinx-design:     0.4.1
	- sphinx-rtd-theme:  1.2.2
	- sphinxcontrib-applehelp: 1.0.4
	- sphinxcontrib-devhelp: 1.0.2
	- sphinxcontrib-htmlhelp: 2.0.1
	- sphinxcontrib-jquery: 4.1
	- sphinxcontrib-jsmath: 1.0.1
	- sphinxcontrib-programoutput: 0.15
	- sphinxcontrib-qthelp: 1.0.3
	- sphinxcontrib-serializinghtml: 1.1.9
	- stack-data:        0.6.2
	- stdlib-list:       0.6.0
	- sympy:             1.11.1
	- tensorboard:       2.13.0
	- tensorboard-data-server: 0.7.0
	- tensorboard-plugin-wit: 1.8.1
	- terminado:         0.17.1
	- threadpoolctl:     3.1.0
	- tifffile:          2023.8.30
	- timm:              0.9.2
	- tinycss2:          1.2.1
	- tokenize-rt:       4.2.1
	- tomli:             2.0.1
	- tomli-w:           1.0.0
	- torch:             2.1.0
	- torchmetrics:      1.2.0
	- torchvision:       0.16.0
	- tornado:           6.3.3
	- tqdm:              4.66.1
	- traitlets:         5.9.0
	- trove-classifiers: 2023.8.7
	- twine:             4.0.2
	- typeshed-client:   2.1.0
	- typing-extensions: 4.8.0
	- uri-template:      1.2.0
	- urllib3:           1.26.12
	- vermin:            1.5.2
	- wcwidth:           0.2.7
	- webcolors:         1.11.1
	- webencodings:      0.5.1
	- websocket-client:  1.6.3
	- werkzeug:          3.0.0
	- wheel:             0.37.1
	- widgetsnbextension: 4.0.3
	- xarray:            2023.7.0
	- yarl:              1.9.2
	- zipfile-deflate64: 0.2.0
	- zipp:              3.17.0
	- zope.event:        4.6
	- zope.interface:    5.4.0
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		- 
	- processor:         arm
	- python:            3.11.6
	- release:           23.0.0
	- version:           Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020

</details>

### More info

@carmocca @awaelchli 

cc @awaelchli

**Comment by carmocca** [comment]
Sorry about this. I opened #18859.

Ideally we would have a job in CI without distributed, but AFAIK this can only be accomplished if PyTorch is built from source, and that would require setting up the entire dependency chain to compile it.

**Comment by awaelchli** [comment]
We added a test for this a while ago to cover the import paths: https://github.com/Lightning-AI/lightning/blob/1210deb5a0ff720b0ad66e38149cd28471d760ca/tests/tests_fabric/utilities/test_imports.py#L21
But this error here seems to be happening at runtime, so as @carmocca says we probably can't cover this one so easily.

**Comment by adamjstewart** [comment]
Thanks for the quick fix!
