### ISSUE TITLE
AttributeError: 'MyCustomLogger' object has no attribute 'experiment'

### ISSUE THREAD

**Issue by austin-bowen** [Lightning-AI/lightning#18061]
### Bug description

I have a custom logger subclassing `lightning.fabric.loggers.Logger` that was working in 2.0.3, but now fails in 2.0.5 with this error:

```
 File "/opt/conda/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 78, in _call_setup_hook
 _ = logger.experiment
 AttributeError: 'SageMakerLogger' object has no attribute 'experiment'
```

It seems from lightning 2.0.3 to 2.0.5, a requirement was introduced for `Logger` instances to have an `experiment` attribute, in `lightning/pytorch/trainer/call.py` `_call_setup_hook(trainer)`:

```python
# Trigger lazy creation of experiment in loggers so loggers have their metadata available
for logger in trainer.loggers:
    _ = logger.experiment
```

However, this new property is not specified as required in `lightning.fabric.loggers.Logger`, and as my custom logger does not have that property, it causes an AttributeError.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
This works in 2.0.3, but fails in 2.0.5 with `AttributeError: 'SageMakerLogger' object has no attribute 'experiment'`:


from lightning.pytorch.loggers import Logger


class MyCustomLogger(Logger):
    @property
    def name(self) -> Optional[str]:
        return ''

    @property
    def version(self) -> Optional[Union[int, str]]:
        return None

    @rank_zero_only
    def log_metrics(self, metrics: Dict[str, float], step: Optional[int] = None) -> None:
        ...

    def log_hyperparams(self, params: Union[Dict[str, Any], Namespace], *args: Any, **kwargs: Any) -> None:
        pass


trainer = Trainer(
    ...,
    logger=[MyCustomLogger()],
)

trainer.fit(...)
```

### Error messages and logs

```
 File "/opt/conda/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 78, in _call_setup_hook
 _ = logger.experiment
 AttributeError: 'SageMakerLogger' object has no attribute 'experiment'
```

### Environment

<details>
  <summary>Current environment</summary>

```
- Lightning Component: Trainer, Logger
- PyTorch Lightning Version: 2.0.5
- Lightning App Version: 2.0.5
- PyTorch Version: 2.0.1
- Python version: 3.10
- OS: Linux
#- CUDA/cuDNN version:
#- GPU models and configuration:
- How you installed Lightning: pip
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@austin-bowen 
I'm sorry, I assumed that since all our loggers have this experiment property implemented, we had it as part of the base class. We can modify this code here

https://github.com/Lightning-AI/lightning/blob/00496da92d9e7d17c81f51c9abfb54583ba2817f/src/lightning/pytorch/trainer/call.py#L82C1-L85

to check whether the attribute exists and only call it when it does.
