### PR TITLE
Allow custom loggers without an experiment property

### LINKED ISSUE #18061: AttributeError: 'MyCustomLogger' object has no attribute 'experiment'
### Bug description

I have a custom logger subclassing `lightning.fabric.loggers.Logger` that was working in 2.0.3, but now fails in 2.0.5 with this error:

```
 File "/opt/conda/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 78, in _call_setup_hook
 _ = logger.experiment
 AttributeError: 'SageMakerLogger' object has no attribute 'experiment'
```

It seems from lightning 2.0.3 to 2.0.5, a requirement was introduced for `Logger` instances to have an `experiment` attribute, in `lightning/pytorch/trainer/call.py` `_call_setup_hook(trainer)`:

```python
# Trigger lazy creation of experiment in loggers so loggers have their metadata available
for logger in trainer.loggers:
    _ = logger.experiment
```

However, this new property is not specified as required in `lightning.fabric.loggers.Logger`, and as my custom logger does not have that property, it causes an AttributeError.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
This works in 2.0.3, but fails in 2.0.5 with `AttributeError: 'SageMakerLogger' object has no attribute 'experiment'`:


from lightning.pytorch.loggers import Logger


class MyCustomLogger(Logger):
    @property
    def name(self) -> Optional[str]:
        return ''

    @property
    def version(self) -> Optional[Union[int, str]]:
        return None

    @rank_zero_only
    def log_metrics(self, metrics: Dict[str, float], step: Optional[int] = None) -> None:
        ...

    def log_hyperparams(self, params: Union[Dict[str, Any], Namespace], *args: Any, **kwargs: Any) -> None:
        pass


trainer = Trainer(
    ...,
    logger=[MyCustomLogger()],
)

trainer.fit(...)
```

### Error messages and logs

```
 File "/opt/conda/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 78, in _call_setup_hook
 _ = logger.experiment
 AttributeError: 'SageMakerLogger' object has no attribute 'experiment'
```

### Environment

<details>
  <summary>Current environment</summary>

```
- Lightning Component: Trainer, Logger
- PyTorch Lightning Version: 2.0.5
- Lightning App Version: 2.0.5
- PyTorch Version: 2.0.1
- Python version: 3.10
- OS: Linux
#- CUDA/cuDNN version:
#- GPU models and configuration:
- How you installed Lightning: pip
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

### More info

_No response_

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do?

Fixes #18061
Follow up to #17818

The experiment property is not part of the interface definition, therefore we can't assume it to be accessible.

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

cc @awaelchli @borda @Blaizzy

### CODE REVIEW

**Review by Borda — APPROVED** [review]

File: src/lightning/pytorch/trainer/call.py [hunk 1]
```diff
@@ -82,7 +82,8 @@ def _call_setup_hook(trainer: "pl.Trainer") -> None:
 
     # Trigger lazy creation of experiment in loggers so loggers have their metadata available
     for logger in trainer.loggers:
-        _ = logger.experiment
+        if hasattr(logger, "experiment"):
```
Comment (carmocca) [inline src/lightning/pytorch/trainer/call.py:85]: This should check if the attr exists before looping

Comment (awaelchli) [reply src/lightning/pytorch/trainer/call.py:85]: I don't understand. We need to loop over all loggers anyway.
